apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/GordonTMcgaffin/Cluster-Apps.git
    targetRevision: HEAD
    path: applications/
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
