apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 8gears.container-registry.com/library/n8n
    chart: n8n
    targetRevision: 1.0.10
    helm:
      values: |-
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
