apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 8gears.container-registry.com/library
    chart: n8n
    targetRevision: 1.0.10
    helm:
      values: |-
        env:
          WEBHOOK_URL: "https://pudding.mcmuffin.co.za/n8n/"
          N8N_EDITOR_BASE_URL: "https://pudding.mcmuffin.co.za/n8n/"
          N8N_PATH: "/n8n"
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
