apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-main
  namespace: default  # or "default" if that's where Argo CD is running
spec:
  project: default
  source:
    repoURL: https://github.com/n8n-io/n8n
    targetRevision: 1.0.7
    chart: n8n
    helm:
      values: |-
        main:
          resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
